name: NPM Publish
on:
  release:
    types: [created]

jobs:
  install-test-build-dist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
      - run: rm -f ./yarn.lock
      - run: yarn install --disable-pnp
      - run: yarn test
      - run: yarn build
      - run: yarn publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
